---
- name: install zabbix-agetn
  hosts: all
  gather_facts: yes
  become: yes
  tasks:
    - name: install wget
      yum:
        name: wget
        state: present

#    - name: copy zabbix agent rpm
#      shell: "wget https://repo.zabbix.com/zabbix/5.0/rhel/7/x86_64/zabbix-release-5.0-1.el7.noarch.rpm"
#      args:
#        warn: no

#    - name: clean yum
#      shell: "yum -y lovalinstall zabbix-release-5.0-1.el7.noarch.rpm"

    - name: install epel-release
      shell: "yum -y install epel-release"
      
    - name: install zabbix-agent
      shell: "yum -y install zabbix-agent"

    - name: config zabbix agent
      template:
        src: zabbix-agentd.conf.j2
        dest: /etc/zabbix_agentd.conf
        owner: root
        group: root

#    - name: start zabbix agent
#      service:
#        name: zabbix agent
#        state: started
#        enable: true
